#!/usr/bin/env python3
"""Generate the App manifests and the Wave ApplicationSets from one definition.

Usage: generate-waves.py [--definition gitops/waves.toml] [--out gitops]

Writes OUT/apps/<app>/ (podinfo Deployment, Service, HTTPRoute) for every App
and OUT/waves/wave-<n>/applicationset.yaml for every Wave. Both folders are
owned by this script: they are replaced on every run, so never edit them.
Exits non-zero, writing nothing, if the definition breaks a rule.
"""
import argparse
import shutil
import sys
import tomllib
from pathlib import Path

REPO_URL = "https://github.com/arsanurak/platform-demo.git"
REVISION = "main"
PODINFO_IMAGE = (
    "ghcr.io/stefanprodan/podinfo:6.15.0"
    "@sha256:ec73780a8425f59ea49f5bc8cdff0d598805a224fbaa1f86c67a244f250fa9da"
)
HEADER = "# Generated by scripts/generate-waves.py from gitops/waves.toml. Do not edit.\n"


def check(definition):
    """Return the list of rule violations in the definition (empty if valid)."""
    apps = definition.get("apps", {})
    waves = [wave.get("apps", []) for wave in definition.get("waves", [])]
    errors = []
    wave_of = {}
    for number, members in enumerate(waves, start=1):
        if not members:
            errors.append(f"wave {number} has no apps")
        for app in members:
            if app not in apps:
                errors.append(f"wave {number} names {app}, which is not an app")
            elif app in wave_of:
                errors.append(f"{app} is in wave {wave_of[app]} and wave {number}")
            else:
                wave_of[app] = number
    for app, settings in apps.items():
        if app not in wave_of:
            errors.append(f"{app} is in no wave")
        callee = settings.get("calls")
        if callee is None:
            continue
        if callee not in apps:
            errors.append(f"{app} calls {callee}, which is not an app")
        elif app in wave_of and callee in wave_of and wave_of[callee] >= wave_of[app]:
            errors.append(
                f"{app} calls {callee}, so it must be in a later wave "
                f"(it is in wave {wave_of[app]}, {callee} in wave {wave_of[callee]})"
            )
    return errors


def deployment(app, settings):
    args = ["./podinfo", "--port=9898", "--level=info", "--data-path=/data"]
    callee = settings.get("calls")
    if callee:
        args.append(f"--backend-url=http://{callee}.{callee}.svc.cluster.local/echo")
    command = "".join(f"            - {arg}\n" for arg in args)
    comment = f"# {app} calls {callee} through podinfo's backend URL: POST /api/echo is forwarded to it.\n" if callee else ""
    return f"""{HEADER}{comment}apiVersion: apps/v1
kind: Deployment
metadata:
  name: {app}
  namespace: {app}
  labels:
    app.kubernetes.io/name: {app}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {app}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {app}
    spec:
      # The podinfo image's own user and group, as numbers so runAsNonRoot can check them.
      securityContext:
        runAsNonRoot: true
        runAsUser: 100
        runAsGroup: 101
        fsGroup: 101
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: podinfo
          image: {PODINFO_IMAGE}
          command:
{command}          env:
            - name: PODINFO_UI_MESSAGE
              value: {app}
          ports:
            - name: http
              containerPort: 9898
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              memory: 64Mi
          securityContext:
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          # podinfo's only writable path; the root filesystem stays read-only.
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          emptyDir: {{}}
"""


def service(app):
    return f"""{HEADER}apiVersion: v1
kind: Service
metadata:
  name: {app}
  namespace: {app}
spec:
  selector:
    app.kubernetes.io/name: {app}
  ports:
    - name: http
      port: 80
      targetPort: http
"""


def httproute(app):
    return f"""{HEADER}# Requests to the cluster Gateway with Host: {app}.example.com reach {app}.
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {app}
  namespace: {app}
spec:
  parentRefs:
    - name: web
      namespace: gateway
  hostnames:
    - {app}.example.com
  rules:
    - backendRefs:
        - name: {app}
          port: 80
"""


def applicationset(number, members):
    elements = "".join(f"        - app: {app}\n" for app in members)
    return f"""{HEADER}# Wave {number}. `make wave-{number}` applies this to the new cluster, after
# waves before it are healthy there. One Application per App, deployed from
# gitops/apps/<app>/ into a namespace named after the App.
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: wave-{number}
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
{elements}  template:
    metadata:
      name: "{{{{ .app }}}}"
      labels:
        platform-demo/wave: "{number}"
    spec:
      project: default
      source:
        repoURL: {REPO_URL}
        targetRevision: {REVISION}
        path: "gitops/apps/{{{{ .app }}}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{{{ .app }}}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 10
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 3m
"""


def write(out, definition):
    for folder in ("apps", "waves"):
        shutil.rmtree(out / folder, ignore_errors=True)
    for app, settings in sorted(definition["apps"].items()):
        folder = out / "apps" / app
        folder.mkdir(parents=True)
        (folder / "deployment.yaml").write_text(deployment(app, settings))
        (folder / "service.yaml").write_text(service(app))
        (folder / "httproute.yaml").write_text(httproute(app))
    for number, wave in enumerate(definition["waves"], start=1):
        folder = out / "waves" / f"wave-{number}"
        folder.mkdir(parents=True)
        (folder / "applicationset.yaml").write_text(applicationset(number, wave["apps"]))


def main():
    repo_root = Path(__file__).resolve().parent.parent
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--definition", type=Path, default=repo_root / "gitops" / "waves.toml")
    parser.add_argument("--out", type=Path, default=repo_root / "gitops")
    args = parser.parse_args()

    definition = tomllib.loads(args.definition.read_text())
    errors = check(definition)
    if errors:
        for error in errors:
            print(f"{args.definition}: {error}", file=sys.stderr)
        return 1
    write(args.out, definition)
    return 0


if __name__ == "__main__":
    sys.exit(main())
